version: "3"
networks:
  app-tier:
    driver: bridge
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: php:apache-plus
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    command: 
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: qaz@123
      MYSQL_DATABASE: prova2php
      MYSQL_USER: root
      MYSQL_PASSWORD: qaz@123
    networks:
      - app-tier
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
